### ISSUE TITLE
no graspitGUI.h when compiling graspit_eval_plugin

### ISSUE THREAD

**Issue by emigmo** [ShapeCompletion3D/graspit_eval_plugin#1]
/home/dex_hand/urbh_ws/src/graspit_eval_plugin/src/graspit_eval_interface.cpp:45:32: fatal error: include/graspitGUI.h: No such file or directory
 #include <include/graspitGUI.h>
                                ^
compilation terminated.
make[2]: *** [graspit_eval_plugin/CMakeFiles/graspit_eval_interface.dir/src/graspit_eval_interface.cpp.o] Error 1
make[1]: *** [graspit_eval_plugin/CMakeFiles/graspit_eval_interface.dir/all] Error 2

**Comment by jvarley** [comment]
If you are looking to run the shape completion code, I am currently working on a tutorial for it here:
https://github.com/CURG/pc_pipeline_launch/blob/master/README.md although it is still a work in progress. 

If you want to run this graspit plugin, graspitGUI.h has been replaced with graspitCore.h.  You may have to change it in a few locations.  If you get it to compile again, please make a PR.

**Comment by emigmo** [comment]
Too many bugs which I'm trying to repair , Could do know which version of graspit the graspit_eval_plugin has used.  I'm finding the "ENERGY_CONTACT_QUALITY" and "searchEnergy.h" of this version is not right.
By the way, I just want use the graspit_eval_plugin to generate the grasp pose from the completed 3D model .

**Comment by jvarley** [comment]
Ill see if I can fix this up a bit.  For the most recent version of the paper, I ended up not using this repo, I used graspit commander to do my grasp evaluation.

https://github.com/graspit-simulator/graspit_commander

Its easy to script using it to using something like:
def evaluate_pregrasp(pre_grasp):
    GraspitCommander.toggleAllCollisions(False)
    GraspitCommander.forceRobotDof([0,0,0,0])
    GraspitCommander.setRobotPose(pre_grasp.pose)
    GraspitCommander.toggleAllCollisions(True)
    GraspitCommander.findInitialContact()
    GraspitCommander.approachToContact(200)
    GraspitCommander.autoGrasp()
    result = GraspitCommander.getRobot(0)
    return result

**Comment by jvarley** [comment]
This package should compile for you now with the master branch of graspit-ros. I tested on 14.04 ubuntu with ROS Indigo.

**Comment by emigmo** [comment]
yes, I will try to use your way to do grasp evaluation.
Can I ask a question, in the graspit package, object, obstacle and robot describing in .iv format.
how can i change the object model (.stl or .ply) to the .iv format

**Comment by jvarley** [comment]
Graspit can load iv, ply, off, and wrl files. So just use ply if you have them.  If you decide you want to make iv files, look at ivcon. http://wiki.ros.org/ivcon
